apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-discord.fullname" . }}
  labels:
{{ include "mautrix-discord.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Values.config | toYaml) . | b64enc | quote }}
  registration.yaml: {{ tpl (.Values.registration | toYaml) . | b64enc | quote }}

